### ISSUE TITLE
ask questions about AbstractMyBatisModule,TKS!

### ISSUE THREAD

**Issue by KING754** [mybatis/guice#130]
mycode:
`public class DmXmlMybatisMoudle extends AbstractMyBatisModule{
....
    	@Override
	final void internalConfigure() {
             Reader reader = null;
		try {
			File config = getConfig();
			if (null == config) {
				LOGGER.error("config file is null. mybatis-cfg.xml path={}", this.classPathResource);
			}
			
//			super.install(JdbcHelper.MySQL);
			reader = new BufferedReader(new InputStreamReader(new FileInputStream(config), "utf8"));
			LOGGER.info("load outer mybatis config:{}", config.getCanonicalPath());
                      	SqlSessionFactory sessionFactory = new SqlSessionFactoryBuilder().build(reader, environmentId, properties);
			bind(SqlSessionFactory.class).toInstance(sessionFactory);
                        ....same with "XMLMyBatisModule.java"
        }catch(){
        }finally{
        }
}

public GuiceFactory{
      public synchronized GuiceFactory init(){
              List<Module> bindingModules = new ArrayList<Module>();
              bindingModules.add(new DmXmlMybatisMoudle());
              try{
                      this.injector = Guice.createInjector(Stage.PRODUCTION, bindingModules);
              }catch(Exception e){
                      LOGGER.error(e.getMessage(),e);
              }
      }
}
/////////////////////////////////////
but when i call init(),have a exception.
Exception in thread "main" java.lang.NoSuchMethodError: org.mybatis.guice.AbstractMyBatisModule.bindInterceptor(Lcom/google/inject/matcher/Matcher;Lcom/google/inject/matcher/Matcher;[Lorg/aopalliance/intercept/MethodInterceptor;)V
	at org.mybatis.guice.AbstractMyBatisModule.bindTransactionInterceptors(AbstractMyBatisModule.java:80)
	at org.mybatis.guice.AbstractMyBatisModule.configure(AbstractMyBatisModule.java:64)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
`

i  am so sorry,i can not find the exception`s root reason. 
tks

**Comment by KING754** [comment]
i am found the exception,from there:
abstract class AbstractMyBatisModule extends AbstractModule
--->protected void bindTransactionInterceptors()
--->bindInterceptor(any(), not(SYNTHETIC).and(not(DECLARED_BY_OBJECT)).and(annotatedWith(Transactional.class)),interceptor);

before the exception,i watch about vars,
any()　=　any()

not(SYNTHETIC).and(not(DECLARED_BY_OBJECT)).and(annotatedWith(Transactional.class))　=　
and(and(not(org.mybatis.guice.AbstractMyBatisModule$2@33ae7f61), not(org.mybatis.guice.AbstractMyBatisModule$1@52cd3c9)), annotatedWith(Transactional.class))

interceptor　=　org.mybatis.guice.transactional.TransactionalMethodInterceptor@7550004f

**Comment by christianpoitras** [comment]
You are right that the exception could be more explicit. But I guess that most people are not using a custom module extending `AbstractMyBatisModule` in addition to using a non-AOP Guice. Otherwise, this exception message improvement would have been reported sooner.

**Comment by KING754** [comment]
haha,you are right.it is careless error.
i create a custom module extending AbstractMyBatisModule. main reason is the internalConfigure function about the reader code.i ovrride it:
"
File config = getConfig();
if (null == config) {
       LOGGER.error("config file is null. mybatis-cfg.xml path={}", this.classPathResource);
}
reader = new BufferedReader(new InputStreamReader(new FileInputStream(config), "utf8"));
"
finally,thanks to you.i am go to bed.
