### ISSUE TITLE
Support Guice 4.0

### ISSUE THREAD

**Issue by yochaude** [mybatis/guice#46]
Embedding mybatis-guice (latest version) in a project using Guice 4.0 results in the following run time error:

```
java.lang.NoClassDefFoundError: com/google/inject/internal/util/$Preconditions
	at org.mybatis.guice.MyBatisModule.internalConfigure(MyBatisModule.java:84)
	at org.mybatis.guice.AbstractMyBatisModule.configure(AbstractMyBatisModule.java:59)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
```

Maybe just relying on the Preconditions class from Guava instead of this internal copy would resolve the issue "smoothly"?

**Comment by jeffgbutler** [comment]
MyBatis Guice has supported Guice 4.0 for quite some time - I'm using it myself on a couple of projects.  Are you sure your are using a recent version of mybatis-guice?  From the line numbers in your stack trace it looks like you are a few versions behind (they look like line number from version 3.3 and 3.7 is current).

**Comment by yochaude** [comment]
Dang! You are right... I updated a bunch of other non related libs and was pretty sure I did the same for mybatis-guice. No excuse, my mistake :)

I upgraded to 3.7 and all is good.

Thanks! And sorry for the noise.
